server:
  port: 8080

logging:
  level:
    com.lyj.blog.mapper: debug

spring:
  freemarker:
    cache: false


myConfig:
  file:
    location: ./upload
  host: localhost
  elasticsearch:
    url: localhost:9200
