mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.lyj.blog.mapper: info


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: true
    charset: utf-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:templates
  resources:
    static-locations: classpath:/static/,file:${file.location}

file:
  location: /upload

host: luyingjie.cn