server:
  port: 80

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.lyj.blog.mapper: info


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: true
    charset: utf-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:templates
  resources:
    static-locations: classpath:/static/,file:${file.location}
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678

file:
  location: /upload

host: luyingjie.cn

elasticsearch:
  hostAndPort: 47.105.165.211:9200