server:
  port: 80

logging:
  level:
    com.lyj.blog.mapper: info

spring:
  freemarker:
    cache: true

myConfig:
  file:
    location: /upload
  host: luyingjie.cn
  elasticsearch:
    url: 47.105.165.211:9200